"""sync database with current models

Revision ID: 27283e91d2f8
Revises: a1b2c3d4e5f6
Create Date: 2026-07-07 12:20:41.329773+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27283e91d2f8'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_targets',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False, comment='department | position | role | user'),
    sa.Column('target_value', sa.String(length=255), nullable=False, comment='UUID برای department/position/user — نام role برای role'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'target_type', 'target_value', name='uq_content_target')
    )
    op.create_index(op.f('ix_content_targets_content_id'), 'content_targets', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_targets_org_id'), 'content_targets', ['org_id'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               comment='ایمیل یکتا در سطح سیستم (نه فقط سازمان) — یکتایی در DB اجرا می\u200cشود',
               existing_comment='ایمیل یکتا در سطح سیستم (نه فقط سازمان)',
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               comment='ایمیل یکتا در سطح سیستم (نه فقط سازمان)',
               existing_comment='ایمیل یکتا در سطح سیستم (نه فقط سازمان) — یکتایی در DB اجرا می\u200cشود',
               existing_nullable=False)
    op.drop_index(op.f('ix_content_targets_org_id'), table_name='content_targets')
    op.drop_index(op.f('ix_content_targets_content_id'), table_name='content_targets')
    op.drop_table('content_targets')
    # ### end Alembic commands ###
