"""sync database with current models

Revision ID: 27283e91d2f8
Revises: a1b2c3d4e5f6
Create Date: 2026-07-07 12:20:41.329773+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27283e91d2f8'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # نکته: op.create_table('content_targets', ...) این‌جا عمداً حذف شده —
    # این جدول از قبل توسط migration a1b2c3d4e5f6 (روی همین شاخه، پدر این
    # نسخه) ساخته می‌شود؛ نسخه‌ی اصلی auto-generate باعث خطای
    # DuplicateTable در اجرای «alembic upgrade head» روی دیتابیس خالی می‌شد.
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               comment='ایمیل یکتا در سطح سیستم (نه فقط سازمان) — یکتایی در DB اجرا می\u200cشود',
               existing_comment='ایمیل یکتا در سطح سیستم (نه فقط سازمان)',
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               comment='ایمیل یکتا در سطح سیستم (نه فقط سازمان)',
               existing_comment='ایمیل یکتا در سطح سیستم (نه فقط سازمان) — یکتایی در DB اجرا می\u200cشود',
               existing_nullable=False)
    # نکته: drop_table('content_targets') عمداً حذف شده — این جدول متعلق به
    # migration a1b2c3d4e5f6 است و downgrade آن باید مسئول حذفش باشد.
    # ### end Alembic commands ###
