"""initial schema

Revision ID: 5d427d3827dd
Revises: 
Create Date: 2026-06-28 08:39:18.116202+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d427d3827dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('slug', sa.String(length=100), nullable=False, comment='شناسه یکتا برای URL — مثال: my-company'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='نام رسمی سازمان'),
    sa.Column('name_en', sa.String(length=255), nullable=True, comment='نام انگلیسی (اختیاری)'),
    sa.Column('logo_url', sa.String(length=500), nullable=True, comment='آدرس لوگو در MinIO'),
    sa.Column('description', sa.Text(), nullable=True, comment='درباره سازمان — نمایش در صفحه معرفی'),
    sa.Column('mission', sa.Text(), nullable=True, comment='ماموریت سازمان'),
    sa.Column('vision', sa.Text(), nullable=True, comment='چشم\u200cانداز سازمان'),
    sa.Column('values', sa.Text(), nullable=True, comment='ارزش\u200cهای سازمانی'),
    sa.Column('culture', sa.Text(), nullable=True, comment='فرهنگ سازمانی'),
    sa.Column('history', sa.Text(), nullable=True, comment='تاریخچه سازمان'),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='تنظیمات سازمان مثل رنگ، فونت، ویژگی\u200cهای فعال'),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('departments',
    sa.Column('org_id', sa.UUID(), nullable=False, comment='کلید اصلی جداسازی سازمان\u200cها'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='نام واحد — مثال: واحد فناوری'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='واحد مادر برای ساختار درختی'),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='ترتیب نمایش در چارت سازمانی'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_org_id'), 'departments', ['org_id'], unique=False)
    op.create_table('positions',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False, comment='عنوان پست — مثال: مدیر محصول'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False, comment='سطح سازمانی: 1=کارمند، 5=مدیرعامل'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_org_id'), 'positions', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('org_id', sa.UUID(), nullable=False, comment='سازمان کاربر — Row-Level Security'),
    sa.Column('manager_id', sa.UUID(), nullable=True, comment='مدیر مستقیم کاربر'),
    sa.Column('email', sa.String(length=320), nullable=False, comment='ایمیل یکتا در سطح سیستم (نه فقط سازمان)'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='نام و نام خانوادگی'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcrypt hash — هرگز plain text ذخیره نکنید'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='super_admin | org_admin | manager | employee'),
    sa.Column('dept_id', sa.UUID(), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='آدرس تصویر پروفایل در MinIO'),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='غیرفعال کردن بدون حذف'),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_manager_id'), 'users', ['manager_id'], unique=False)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('contents',
    sa.Column('org_id', sa.UUID(), nullable=False, comment='کلید اصلی جداسازی سازمان\u200cها'),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False, comment='course | article | podcast | book'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True, comment='آدرس تصویر کاور در MinIO'),
    sa.Column('author', sa.String(length=255), nullable=True, comment='نام نویسنده یا مدرس'),
    sa.Column('instructor_name', sa.String(length=255), nullable=True, comment='مدرس (برای دوره\u200cها)'),
    sa.Column('instructor_avatar_url', sa.String(length=500), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False, comment='تگ\u200cها برای فیلتر و جستجو'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='draft | published | archived'),
    sa.Column('level', sa.String(length=50), nullable=True, comment='beginner | intermediate | advanced'),
    sa.Column('total_duration_min', sa.Integer(), nullable=True, comment='مدت زمان کل به دقیقه'),
    sa.Column('total_items_count', sa.Integer(), nullable=False, comment='تعداد آیتم\u200cها — برای نمایش سریع'),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='اطلاعات اضافی مثل ISBN کتاب، URL پادکست'),
    sa.Column('is_featured', sa.Boolean(), nullable=False, comment='محتوای ویژه — نمایش در صفحه اول'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_org_id'), 'contents', ['org_id'], unique=False)
    op.create_table('invitations',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False, comment='کاربری که دعوت فرستاده'),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False, comment='توکن یکبار مصرف برای ثبت\u200cنام'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='72 ساعت بعد از ارسال منقضی می\u200cشود'),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True, comment='زمان قبول دعوت — null یعنی هنوز استفاده نشده'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_org_id'), 'invitations', ['org_id'], unique=False)
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_table('onboarding_programs',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False, comment='نام برنامه — مثال: برنامه آشنایی کارمندان جدید'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_roles', postgresql.ARRAY(sa.String()), nullable=False, comment='نقش\u200cهای هدف — خالی یعنی همه'),
    sa.Column('target_dept_id', sa.UUID(), nullable=True, comment='واحد هدف — null یعنی همه واحدها'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='ثبت\u200cنام خودکار برای کارمندان جدید'),
    sa.Column('deadline_days', sa.Integer(), nullable=True, comment='مهلت تکمیل — null یعنی بدون مهلت'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_dept_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_programs_org_id'), 'onboarding_programs', ['org_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pass_score', sa.Integer(), nullable=False, comment='نمره قبولی — درصد از 100'),
    sa.Column('time_limit_min', sa.Integer(), nullable=True, comment='مهلت پاسخگویی به دقیقه — null یعنی نامحدود'),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=False),
    sa.Column('shuffle_options', sa.Boolean(), nullable=False),
    sa.Column('is_onboarding', sa.Boolean(), nullable=False, comment='آزمون ورودی سازمان'),
    sa.Column('max_attempts', sa.Integer(), nullable=True, comment='null یعنی می\u200cتوان بارها شرکت کرد'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_org_id'), 'quizzes', ['org_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False, comment='برای جداسازی سریع\u200cتر query'),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='SHA256 hash از refresh token'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='زمان revoke — اگر null باشد هنوز معتبر است'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_org_id'), 'refresh_tokens', ['org_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('content_items',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False, comment='text | video | pdf | image | link | file | quiz_ref'),
    sa.Column('body', sa.Text(), nullable=True, comment='محتوای Rich Text برای type=text'),
    sa.Column('media_url', sa.String(length=1000), nullable=True, comment='آدرس فایل در MinIO یا URL خارجی'),
    sa.Column('quiz_id', sa.UUID(), nullable=True, comment='شناسه Quiz اگر type=quiz_ref باشد'),
    sa.Column('duration_min', sa.Integer(), nullable=True, comment='مدت زمان به دقیقه'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='ترتیب نمایش آیتم\u200cها'),
    sa.Column('is_free', sa.Boolean(), nullable=False, comment='آیا بدون ثبت\u200cنام قابل مشاهده است؟'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_content_id'), 'content_items', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_items_org_id'), 'content_items', ['org_id'], unique=False)
    op.create_table('program_steps',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False, comment='content | quiz | document_upload | custom'),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('quiz_id', sa.UUID(), nullable=True, comment='آزمون اختیاری — null یعنی آزمون ندارد'),
    sa.Column('is_required', sa.Boolean(), nullable=False, comment='آیا تکمیل این مرحله اجباری است؟'),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['onboarding_programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_steps_org_id'), 'program_steps', ['org_id'], unique=False)
    op.create_index(op.f('ix_program_steps_program_id'), 'program_steps', ['program_id'], unique=False)
    op.create_table('questions',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False, comment='متن سوال'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='single_choice | multi_choice | true_false | short_text'),
    sa.Column('explanation', sa.Text(), nullable=True, comment='توضیح پاسخ درست — نشان داده می\u200cشود بعد از ارسال'),
    sa.Column('score', sa.Integer(), nullable=False, comment='امتیاز این سوال'),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_org_id'), 'questions', ['org_id'], unique=False)
    op.create_index(op.f('ix_questions_quiz_id'), 'questions', ['quiz_id'], unique=False)
    op.create_table('user_program_enrollments',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('enrolled_by', sa.UUID(), nullable=True, comment='چه کسی ثبت\u200cنام کرده — null یعنی خودکار'),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrolled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['onboarding_programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_program_enrollments_org_id'), 'user_program_enrollments', ['org_id'], unique=False)
    op.create_index(op.f('ix_user_program_enrollments_program_id'), 'user_program_enrollments', ['program_id'], unique=False)
    op.create_index(op.f('ix_user_program_enrollments_user_id'), 'user_program_enrollments', ['user_id'], unique=False)
    op.create_table('question_options',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False, comment='متن گزینه'),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_options_question_id'), 'question_options', ['question_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False, comment='امتیاز کسب شده'),
    sa.Column('max_score', sa.Integer(), nullable=False, comment='حداکثر امتیاز ممکن'),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False, comment='درصد — score/max_score * 100'),
    sa.Column('passed', sa.Boolean(), nullable=False, comment='قبول شده؟ percentage >= pass_score'),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='تاریخچه کامل پاسخ\u200cها — هرگز UPDATE نکنید'),
    sa.Column('duration_sec', sa.Integer(), nullable=True, comment='مدت زمان پاسخ به ثانیه'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['program_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_org_id'), 'quiz_attempts', ['org_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('user_content_progress',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('last_item_id', sa.UUID(), nullable=True),
    sa.Column('completed_items', sa.Integer(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False, comment='درصد پیشرفت 0-100'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_item_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_id', name='uq_user_content')
    )
    op.create_index(op.f('ix_user_content_progress_content_id'), 'user_content_progress', ['content_id'], unique=False)
    op.create_index(op.f('ix_user_content_progress_org_id'), 'user_content_progress', ['org_id'], unique=False)
    op.create_index(op.f('ix_user_content_progress_user_id'), 'user_content_progress', ['user_id'], unique=False)
    op.create_table('user_step_progress',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, comment='not_started | in_progress | completed | skipped'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['user_program_enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['program_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_step_progress_org_id'), 'user_step_progress', ['org_id'], unique=False)
    op.create_index(op.f('ix_user_step_progress_step_id'), 'user_step_progress', ['step_id'], unique=False)
    op.create_index(op.f('ix_user_step_progress_user_id'), 'user_step_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_step_progress_user_id'), table_name='user_step_progress')
    op.drop_index(op.f('ix_user_step_progress_step_id'), table_name='user_step_progress')
    op.drop_index(op.f('ix_user_step_progress_org_id'), table_name='user_step_progress')
    op.drop_table('user_step_progress')
    op.drop_index(op.f('ix_user_content_progress_user_id'), table_name='user_content_progress')
    op.drop_index(op.f('ix_user_content_progress_org_id'), table_name='user_content_progress')
    op.drop_index(op.f('ix_user_content_progress_content_id'), table_name='user_content_progress')
    op.drop_table('user_content_progress')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_org_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_question_options_question_id'), table_name='question_options')
    op.drop_table('question_options')
    op.drop_index(op.f('ix_user_program_enrollments_user_id'), table_name='user_program_enrollments')
    op.drop_index(op.f('ix_user_program_enrollments_program_id'), table_name='user_program_enrollments')
    op.drop_index(op.f('ix_user_program_enrollments_org_id'), table_name='user_program_enrollments')
    op.drop_table('user_program_enrollments')
    op.drop_index(op.f('ix_questions_quiz_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_org_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_program_steps_program_id'), table_name='program_steps')
    op.drop_index(op.f('ix_program_steps_org_id'), table_name='program_steps')
    op.drop_table('program_steps')
    op.drop_index(op.f('ix_content_items_org_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_content_id'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_org_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_quizzes_org_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_onboarding_programs_org_id'), table_name='onboarding_programs')
    op.drop_table('onboarding_programs')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_org_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_contents_org_id'), table_name='contents')
    op.drop_table('contents')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_manager_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_positions_org_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_departments_org_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
